FROM ubuntu:14.04

RUN apt-get install -y software-properties-common\
  && add-apt-repository -y ppa:deadsnakes/ppa \
  && apt update -y \
  && apt-get install -y python3.6 git wget --no-	install-recommends \
  && sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2 \
  && sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.4 1 \
  && wget https://bootstrap.pypa.io/get-pip.py \
  && python3.6 get-pip.py && rm get-pip.py \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3.6 python \
  && pip3 install --upgrade pip setuptools \
  && cd && locale-gen en_AU.UTF-8
ENV LANG en_AU.UTF-8
ENV LANGUAGE en_AU:en
ENV LC_ALL en_AU.UTF-8
ENV FLASK_APP=minitwit
COPY /src /app
WORKDIR /app
RUN pip3 install --editable . \
  && flask initdbEXPOSE 5000
  
CMD [ "flask", "run", "--host=0.0.0.0" ]