FROM python:3.8.0-alpine3.10

ENV FLASK_APP=minitwit
COPY /src /app
WORKDIR /app
RUN apk --no-cache add tzdata \
		&& cp /usr/share/zoneinfo/Australia/Sydney /etc/localtime \
		&& echo "Australia/Sydney" > /etc/timezone \
		&& pip install --no-cache-dir --editable . \
		&& flask initdb
EXPOSE 5000

CMD [ "flask", "run", "--host=0.0.0.0" ]
