FROM ubuntu:14.04

RUN apt-get -y update
RUN apt-get -y install git
RUN apt-get -y install wget
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN apt-get -y install python3-dev
RUN ln -s /usr/bin/python3 python
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN locale-gen en_AU.UTF-8
ENV LANG en_AU.UTF-8
ENV LANGUAGE en_AU:en
ENV LC_ALL en_AU.UTF-8
ENV FLASK_APP=minitwit
COPY /src /app
WORKDIR /app
RUN pip3 install --editable .
RUN flask initdb

EXPOSE 5000
CMD [ "flask", "run", "--host=0.0.0.0" ]